### ISSUE TITLE
Statistics Tutorial 1 (W3D1)

### ISSUE THREAD

**Issue by MennaEltaras** [arabs-in-neuro/intro_to_comp_neuro#7]
Interactive Demo 1.2: Varying parameters of a random walk 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial1_Solution_6e912c89.py

Think 2.1: Binomial distribution sampling 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial1_Solution_06a79c9b.py

Interactive Demo 2.2: Varying parameters of Poisson distribution 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial1_Solution_81eb1b08.py

**Comment by Abdo-programming** [comment]
Updated. Also corrected some spelling mistakes.

**Comment by Abdo-programming** [comment]
Updated. Also corrected some spelling mistakes.
