### ISSUE TITLE
Statistics Tutorial 2 (W3D2)

### ISSUE THREAD

**Issue by MennaEltaras** [arabs-in-neuro/intro_to_comp_neuro#9]
Math Exercise 1.1: Probability example 
A) A product 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_a8e07acd.py
B) Joint probability generally 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_aba8ef46.py
C) Conditional probability 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_75b17480.py
D) Marginal probability 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_b63ebf79.py

Coding Exercise 1.2: Markov chains 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_ca188ef1.py
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_84b223c9.py

Interactive Demo 2.2: Maximum Likelihood inference 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_6338abeb.py

Coding Exercise 2.2: Maximum Likelihood Estimation
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_cf9bfae6.py

Section 2.2.3: Analytical solution 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_696ddd33.py

Think 3.1: Bayesian inference with Gaussian distribution
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_f615551e.py
 
Think 3.2: Bayesian Brains 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_f60d4b5d.py

Bonus Coding Exercise 1: Finding the posterior computationally
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_dfe9474d.py

Bonus Coding Exercise 2: Bayes Net 
https://github.com/NeuromatchAcademy/precourse/tree/main//tutorials/W0D5_Statistics/solutions/W0D5_Tutorial2_Solution_204db048.py

**Comment by Abdo-programming** [comment]
Links updated
